import type { SceneDefinition } from "./types";

export const demoScenes: SceneDefinition[] = [
  {
    id: "scene-intent",
    label: "01 / Intent",
    description:
      "A natural-language prompt becomes a readable graybox scene: one chrome cube with cinematic camera staging.",
    duration: 140,
    background: "#050612",
    fog: { color: "#050612", near: 7, far: 20 },
    camera: {
      start: { position: [0, 1.2, 8], lookAt: [0, 0, 0], fov: 40 },
      end: { position: [0, 0.4, 5.4], lookAt: [0, -0.15, 0], fov: 34 },
    },
    postprocessing: {
      bloom: { intensity: 1.1, luminanceThreshold: 0.16 },
      vignette: { darkness: 0.7 },
      chromaticAberration: { offset: 0.0005 },
    },
    objects: [
      {
        id: "prompt-cube",
        label: "Chrome prompt cube",
        geometry: "box",
        morphTo: "sphere",
        material: "chrome",
        position: [0, 0.4, 0],
        rotation: [0.35, 0.7, 0.14],
        scale: [1.25, 1.25, 1.25],
        color: "#d9f7ff",
        opacity: 1,
        animation: {
          breathe: true,
          pulse: true,
          float: true,
          spin: { axis: "y", speed: 0.22 },
          squashStretch: true,
        },
        visible: true,
      },
      {
        id: "prompt-shadow-ring",
        label: "Soft spatial anchor",
        geometry: "torus",
        material: "hologram",
        position: [0, -1.3, 0],
        rotation: [Math.PI / 2, 0, 0],
        scale: [1.7, 1.7, 0.04],
        color: "#4eeaff",
        opacity: 0.42,
        animation: { pulse: true, spin: { axis: "z", speed: 0.18 } },
        visible: true,
      },
    ],
  },
  {
    id: "scene-choreography",
    label: "02 / Choreography",
    description:
      "Scroll turns static geometry into motion grammar: anticipation, split, orbit, pulse, and semantic morph direction.",
    duration: 170,
    background: "#070512",
    fog: { color: "#070512", near: 7, far: 23 },
    camera: {
      start: { position: [0.2, 0.6, 5.6], lookAt: [0, 0, 0], fov: 37 },
      end: { position: [-1.4, 1.2, 6.2], lookAt: [0.2, 0.1, 0], fov: 42 },
    },
    postprocessing: {
      bloom: { intensity: 1.35, luminanceThreshold: 0.12 },
      vignette: { darkness: 0.8 },
      chromaticAberration: { offset: 0.001 },
    },
    objects: [
      {
        id: "left-shard",
        label: "Left living shard",
        geometry: "box",
        morphTo: "octahedron",
        material: "wireframe",
        position: [-1.35, 0.22, -0.2],
        rotation: [0.4, -0.7, 0.2],
        scale: [0.62, 1.4, 0.62],
        color: "#65f0ff",
        opacity: 0.9,
        animation: { float: true, wobble: true, spin: { axis: "x", speed: 0.4 } },
        visible: true,
      },
      {
        id: "right-shard",
        label: "Right glass shard",
        geometry: "box",
        morphTo: "dodecahedron",
        material: "glass",
        position: [1.35, -0.1, 0.1],
        rotation: [-0.35, 0.8, -0.15],
        scale: [0.62, 1.4, 0.62],
        color: "#a985ff",
        opacity: 0.68,
        animation: { float: true, wobble: true, spin: { axis: "z", speed: -0.36 } },
        visible: true,
      },
      {
        id: "swarm-core",
        label: "Particle morph bridge",
        geometry: "icosahedron",
        morphTo: "sphere",
        material: "emissive",
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        scale: [0.75, 0.75, 0.75],
        color: "#ffffff",
        opacity: 0.92,
        animation: {
          pulse: true,
          breathe: true,
          spin: { axis: "y", speed: 0.75 },
        },
        visible: true,
      },
    ],
  },
  {
    id: "scene-editor",
    label: "03 / Visual Direction",
    description:
      "The canvas becomes editable: every object has identity, metadata, semantic role, and AI-correction hooks.",
    duration: 180,
    background: "#03040a",
    fog: { color: "#03040a", near: 8, far: 24 },
    camera: {
      start: { position: [-1.1, 0.9, 5.8], lookAt: [0, 0, 0], fov: 36 },
      end: { position: [0, 0.4, 4.8], lookAt: [0, -0.05, 0], fov: 32 },
    },
    postprocessing: {
      bloom: { intensity: 1.8, luminanceThreshold: 0.1 },
      vignette: { darkness: 0.86 },
      chromaticAberration: { offset: 0.0008 },
    },
    objects: [
      {
        id: "ai-core",
        label: "Glowing AI core",
        geometry: "sphere",
        morphTo: "torusKnot",
        material: "glow",
        position: [0, 0, 0],
        rotation: [0, 0, 0],
        scale: [1.36, 1.36, 1.36],
        color: "#61f6ff",
        opacity: 0.92,
        animation: {
          breathe: true,
          pulse: true,
          spin: { axis: "y", speed: 0.3 },
          squashStretch: true,
        },
        visible: true,
      },
      {
        id: "semantic-halo",
        label: "Semantic halo timeline",
        geometry: "torusKnot",
        material: "hologram",
        position: [0, 0, 0],
        rotation: [0.3, 0.1, 0.5],
        scale: [2.2, 2.2, 2.2],
        color: "#8c7dff",
        opacity: 0.34,
        animation: { spin: { axis: "y", speed: -0.18 }, pulse: true },
        visible: true,
      },
    ],
  },
];

export const objectIntentMap: Record<string, string[]> = {
  "prompt-cube": [
    "Make this cube hop like it is alive",
    "Slow down the descent by 30%",
    "Morph it into an orb after the split",
  ],
  "prompt-shadow-ring": [
    "Make this feel more like a portal",
    "Increase glow beneath the cube",
  ],
  "left-shard": [
    "Move this shard farther left",
    "Make the shard crack into smaller pieces",
  ],
  "right-shard": [
    "Delay this shard so the motion feels asymmetrical",
    "Make the material more glass-like",
  ],
  "swarm-core": [
    "Increase particle density",
    "Make particles spiral inward faster",
  ],
  "ai-core": [
    "Make this object feel premium and intelligent",
    "Add a stronger breathing pulse",
    "Move it behind the headline",
  ],
  "semantic-halo": [
    "Reduce the halo intensity",
    "Make this timeline ring rotate slower",
  ],
};
